### ISSUE TITLE
testing and docs with tox does not seem to be linked up quite right

### ISSUE THREAD

**Issue by katiebreivik** [wvanzeist/riroriro#11]
When I try `python setup.py test` or `python setup.py build_docs` I receive a description to use tox to build/run the tests or to build the docs. However, If I try `tox -e test` and `tox -e build_docs` I receive the same error: `ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found`.

In the setpy.cfg it looks like pytest and sphinx are used, so I'm a bit turned around. I think one way around this confusion is to add the docs/testing information to the README.rst for folks (like myself) who aren't familiar with the setup, though I'm open to suggestions/explanation!

**Comment by wvanzeist** [comment]
I have made some updates, and the commands `tox -e test` and `tox -e build_docs` should be functional now. Can you check whether they work for you?

**Comment by katiebreivik** [comment]
Thanks - I now can run the tests and build the docs.
