### ISSUE TITLE
ModuleNotFoundError: No module named 'snrcalculatorfuns'

### ISSUE THREAD

**Issue by Krytic** [wvanzeist/riroriro#5]
If I install riroriro from pip, and try `import riroriro.horizondistfuns`, I get the following traceback:

<details>
>>> import riroriro.horizondistfuns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/anaconda3/lib/python3.8/site-packages/riroriro/horizondistfuns.py", line 10, in <module>
    import snrcalculatorfuns as snr
ModuleNotFoundError: No module named 'snrcalculatorfuns'
</details>

I suspect the reason is because riroriro should use `import riroriro.snrcalculatorfuns as snr`.

**Comment by wvanzeist** [comment]
That was a holdover from when the submodules were just files in a folder. It should be fixed in the new release 0.1.2, can you try again and see if it works now?

**Comment by Krytic** [comment]
Looks like it's fixed now :-)

**Comment by wvanzeist** [comment]
Great! The tutorials should now also be updated/fixed as well.
